### PR TITLE
Relax dependencies

### PR DESCRIPTION
**Pull request by ctrueden**
To realign with Labelings/Labeling@d160bc685199e44cf3bb52e27878ff718c71b2a9.

### CODE REVIEW

**Review by tomburke-rse — APPROVED** [review]

**Comment by ctrueden** [comment]
Thanks, @tomburke-rse!

So now @jdeschamps I guess we just need another new release of Labeling, which will trigger another conda-forge PR here, which can be merged...

**Comment by jdeschamps** [comment]
> Thanks, @tomburke-rse!
> 
> So now @jdeschamps I guess we just need another new release of Labeling, which will trigger another conda-forge PR here, which can be merged...

Hi @ctrueden , somehow I missed that. Is it still the case (that we need a new release)?

**Comment by ctrueden** [comment]
@elevans Where are we at? Do we need another Labeling release, to tidy up behavior of downstream conda packages? Or is everything already working now?

**Comment by elevans** [comment]
We do not need another Labeling release. Version `0.1.14` build 1 on conda-forge builds for py312. It resolved our feedstock issues :+1: .

**Pull request merged**
